window.STRINGS_RU = {
  appTitle: "💃 Let's Dance With Me",
  loadingUser: "Загрузка пользователя...",
  loading: "Загрузка...",
  loadingCourses: "Загрузка курсов...",
  loadingLessons: "Загрузка уроков...",
  loadingUsers: "Загрузка...",
  noTelegramData: "Не удалось получить данные Telegram",
  initError: "Ошибка инициализации",
  userDefaultName: "Пользователь",
  roleLabel: "Роль",
  xpLabel: "⭐ XP",
  levelLabel: "🎖 Уровень",
  lessonsDoneLabel: "📚 Пройдено уроков",
  modeTitle: "Режим",
  teacherMode: "Режим преподавателя",
  adminMode: "Режим администратора",
  onboardingTitle: "Добро пожаловать!",
  onboardingText: "Выбери преподавателя и начни обучение.",
  onboardingStart: "Начать",
  studentTitle: "Выбери преподавателя",
  allStyles: "Все направления",
  toTeachers: "⬅ К преподавателям",
  coursesTitle: "Курсы",
  lessonsTitle: "Уроки",
  priceLabel: "Цена",
  purchased: "Куплен",
  notPurchased: "Не куплен",
  buyCourse: "Купить курс за",
  free: "Бесплатно",
  paid: "Платно",
  unlocked: "Открыт",
  locked: "Закрыт",
  noDuration: "без длительности",
  preview: "Превью",
  lessonLockedTitle: "🔒 Урок закрыт",
  lessonLockedNeedPurchase: "Сначала купи курс, чтобы открыть этот урок",
  lessonLockedGeneric: "Этот урок недоступен",
  coursePurchaseSuccess: "Курс успешно куплен",
  teacherCabinet: "Кабинет преподавателя",
  profileTitle: "Профиль",
  teacherNamePh: "Имя преподавателя",
  teacherDescriptionPh: "Описание",
  teacherAvatarPh: "URL аватарки",
  saveProfile: "Сохранить профиль",
  profileSaved: "Профиль сохранен",
  newCourseTitle: "Новый курс",
  courseNamePh: "Название курса",
  courseDescriptionPh: "Описание курса",
  coursePricePh: "Цена",
  published: "Опубликован",
  hidden: "Скрыт",
  createCourse: "Создать курс",
  teacherLessonsTitle: "Уроки курса",
  selectCourse: "Выбери курс",
  noCourses: "Нет курсов",
  noCoursesYet: "Пока нет курсов",
  yourCourses: "Ваши курсы",
  createCourseFirst: "Уроки: сначала создай курс",
  chooseCourse: "Уроки: выбери курс",
  selectedCourseLessons: "Уроки выбранного курса",
  noLessonsYet: "Пока нет уроков",
  lessonNumberPh: "№ урока",
  lessonDurationPh: "Длительность (сек)",
  lessonNamePh: "Название урока",
  lessonPreviewPh: "Ссылка на превью",
  lessonDescriptionPh: "Описание урока",
  lessonFree: "Бесплатный урок",
  lessonPaid: "Платный урок",
  saveLesson: "Сохранить урок",
  updateLesson: "Обновить урок",
  editLesson: "Редактировать",
  lessonSaved: "Урок сохранен",
  courseCreated: "Курс создан",
  needCourseName: "Укажи название курса",
  minCoursePriceError: "Цена курса должна быть не меньше 199 ₽",
  chooseCourseError: "Выбери курс",
  fillLessonError: "Заполни номер и название урока",
  adminPanelTitle: "Админ-панель",
  adminPanelText: "Список пользователей и назначение преподавателей",
  refreshUsers: "Обновить список",
  usersEmpty: "Пользователей пока нет",
  userIdLabel: "ID",
  userRoleLabel: "Роль",
  userLessonsLabel: "Уроков",
  teacherRoleSwitch: "Преподаватель",
  roleUpdated: "Роль обновлена",
  levelDancer: "💃 Танцор",
  levelStudent: "🥋 Ученик",
  levelBeginner: "🌱 Новичок",
  minutes: "мин",
  seconds: "сек"
};
